import { PremiumPageLayout } from "@/components/PremiumPageLayout";
import { Leaf, Recycle, Wind } from "lucide-react";

export default function SustainabilityPage() {
  return (
    <PremiumPageLayout 
      title="Sustainability" 
      subtitle="Engineering for the future means protecting it. We are committed to a zero-waste manufacturing process and carbon-neutral shipping."
    >
      <div className="grid md:grid-cols-3 gap-8 mt-12">
        <div className="p-10 rounded-3xl bg-white border border-black/5 shadow-sm hover:shadow-md transition-shadow">
          <div className="w-14 h-14 bg-brand-teal/10 rounded-2xl flex items-center justify-center mb-8">
            <Recycle className="w-6 h-6 text-brand-teal" />
          </div>
          <h3 className="text-2xl font-medium text-brand-graphite mb-4">Circular Materials</h3>
          <p className="text-brand-graphite/70 leading-relaxed">
            Every Aerio unit is constructed using 85% post-consumer recycled aluminum and bioplastics, designed to be easily disassembled and recycled at the end of its lifecycle.
          </p>
        </div>

        <div className="p-10 rounded-3xl bg-white border border-black/5 shadow-sm hover:shadow-md transition-shadow">
          <div className="w-14 h-14 bg-brand-teal/10 rounded-2xl flex items-center justify-center mb-8">
            <Wind className="w-6 h-6 text-brand-teal" />
          </div>
          <h3 className="text-2xl font-medium text-brand-graphite mb-4">Energy Efficiency</h3>
          <p className="text-brand-graphite/70 leading-relaxed">
            Our proprietary bionic fan design moves 40% more air while using 60% less energy than standard purifiers, earning the highest Energy Star rating in its class.
          </p>
        </div>

        <div className="p-10 rounded-3xl bg-white border border-black/5 shadow-sm hover:shadow-md transition-shadow">
          <div className="w-14 h-14 bg-brand-teal/10 rounded-2xl flex items-center justify-center mb-8">
            <Leaf className="w-6 h-6 text-brand-teal" />
          </div>
          <h3 className="text-2xl font-medium text-brand-graphite mb-4">Biodegradable Filters</h3>
          <p className="text-brand-graphite/70 leading-relaxed">
            We've pioneered the world's first fully biodegradable HEPA filter frame, significantly reducing the plastic waste generated by traditional replacement filters.
          </p>
        </div>
      </div>
    </PremiumPageLayout>
  );
}
